#ifndef ROBOT_H_
#define ROBOT_H_

#define PI 3.1415
#define DEG_TO_RAD(x)    ((float)x * (PI / 180.0))

#define ROBOT_WHEEL_LEFT_PORT   0
#define ROBOT_WHEEL_RIGHT_PORT  1
//#define ROBOT_BALL_THROW_MOTOR_PORT 2
#define ROBOT_RADAR_MOTOR_PORT  3

#define ROBOT_RADAR_SWING  240
#define ROBOT_RADAR_SPEED  5

#define ROBOT_WHEEL_DISTANCE_X   0.2
#define ROBOT_WHEEL_DIAMETER     0.04
#define ROBOT_WHEEL_CIRCUMFERENCE  (ROBOT_WHEEL_DIAMETER * PI)

#define ROBOT_MAP_DIMENSION 2000
#define ROBOT_MAP_OFFSET    (ROBOT_MAP_DIMENSION / 2)

#endif /* ROBOT_H_ */
